spring:
  application:
    name: turbine

server:
  port: 8021
turbine:
  aggregator:
    cluster-config: default
  # 配置Eureka中的serviceId列表，表明监控哪些服务
  app-config: productViewServiceFeign
  cluster-name-expression: new String("default")

#访问 eureka 注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
