#spring boot 的应用程序名 和 thymeleaf 的配置
spring:
  application:
    name: productViewServiceFeign
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    cache: false
    encoding: UTF-8
    servlet:
      content-type: text/html
#配置链路追踪， zipkin 的默认端口为 9411
    zipkin:
      base-url: http://localhost:9411

#访问注册中心， 在 bootstrap.yml 中配置了该信息
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
server:
  port: 8012

#新增路径访问允许：
#这样才能访问 /actuator/bus-refresh
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"

#开启断路器
feign.hystrix.enabled: true

