#spring boot 的应用程序名 和 thymeleaf 的配置
spring:
  application:
    name: productViewServiceFeign
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    cache: false
    encoding: UTF-8
    servlet:
      content-type: text/html
#配置链路追踪， zipkin 的默认端口为 9411
    zipkin:
      base-url: http://localhost:9411

#访问注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8012


